[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mrs-inspector"
version = "0.1.0"
description = "Modular Reasoning Scaffold â€” Inspector"
authors = [{ name = "Anonymous" }]
readme = "README.md"
requires-python = ">=3.9"
license = { file = "LICENSE" }

dependencies = [
    "networkx",
    "graphviz",
    "rich"
]

[project.urls]
Homepage = ""
Documentation = ""
Source = ""
